name: Build & Release

on:
  workflow_dispatch:

permissions:
  contents: write    # necessário para criar tags via API

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # precisa de histórico completo para encontrar tags

      - name: Set Up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.3'
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      # STEP: Bump automático de versão
      - name: Bump version and create tag
        id: bump
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INITIAL_VERSION: '0.0.1'   # versão inicial quando não há tags :contentReference[oaicite:0]{index=0}
          DEFAULT_BUMP: 'patch'      # bump padrão: patch (0.0.1 → 0.0.2) :contentReference[oaicite:1]{index=1}
          WITH_V: 'false'            # omitindo o "v" no prefixo da tag :contentReference[oaicite:2]{index=2}

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.bump.outputs.new_tag }}         # usa a tag criada
          release_name: Release ${{ steps.bump.outputs.new_tag }}
          draft: false
          prerelease: false

      - name: Upload APK to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/app/outputs/apk/release/app-release.apk
          asset_name: app-release.apk
          asset_content_type: application/vnd.android.package-archive
